import { ReduxProvider } from "@/redux/provider"
import ProtectedComponent from "@/app/context/Protected"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
                  <ReduxProvider>
    <ProtectedComponent>
        {children}
        </ProtectedComponent>
        </ReduxProvider></body>
    </html>
  )
}
